services:
  application1:
    build: ./app
    container_name: application1
    ports:
      - "6081:6080"

  application2:
    build: ./app
    container_name: application2
    ports:
      - "6082:6080"

  application3:
    build: ./app
    container_name: application3
    ports:
      - "6083:6080"

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "6080:80"
    depends_on:
      - application1
      - application2
      - application3
